name: PR Style Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
  title:
    name: Title
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            docs
            style
            feat
            test
            build
            ci
            chore
            revert
            release
            api
            deps
            e2e
            extproc
            controller
            translator
            tracing
            examples
            blog
            site
            backport
            cli
            refactor
            mcp
            aigw
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
